version: "3.4"
services:
  user-service:
    image: user-service
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: postgres://user:pass@host.docker.internal:5432/apidb
      JWT_SECRET: MySuperSecretPassPhrase
      WHITELIST_URL: /v0/users
      WHITELISTMETHOD: GET
      PROJECT_NAME: user-services
      PORT: 3000
    restart: always
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb

  admin:
    image: adminer
    restart: always
    depends_on:
      - postgres
    ports:
      - 8080:8080
volumes:
  postgres:
