version: "3.4"
services:
  user-service:
    image: user-service
    ports:
      - "3000:3000"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DATABASE: apidb
      PORT: 3000
      JWT_SECRET: MySuperSecretPassPhrase
      POSTGRES_HOST: 127.0.0.1
      POSTGRES_PORT: 5432
      WHITELIST_URL: "/v0/users"
      WHITELISTMETHOD: "GET"
      PROJECT_NAME: user-services
    restart: always
    depends_on:
      - db
  db:
    image: postgres
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./init-database.sh:/docker-entrypoint-initdb.d/init-database.sh
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: apidb
  admin:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 8080:8080
volumes:
  postgres:
